use alloy_sol_types::sol;

pub const MAX_MATCHES_PER_BATCH: usize = 256;

sol!(
    #[sol(rpc)]
    #[derive(Debug)]
    DarkPool,
    "abi/DarkPool.json"
);

sol!(
    #[sol(rpc)]
    #[derive(Debug)]
    VerifierProxy,
    "abi/VerifierProxy.json"
);

#[cfg(test)]
pub use DarkPool::submitBatchCall;
pub use DarkPool::BatchSettled;
// IDarkPool mod is generated by the sol! macro above because DarkPool.json
// references inputs as `struct IDarkPool.Match[]`. If the ABI is ever changed
// to inline the struct, update this path.
pub use IDarkPool::Match as SolMatch;

#[cfg(feature = "hypernova")]
#[allow(unused_imports)]
pub use DarkPool::{submitSessionCall, settleAuctionCall, SessionSubmitted, AuctionSettled};
