sonar.projectKey=Dnreikronos_DarkPool-Exchange
sonar.organization=dnreikronos
sonar.host.url=https://sonarcloud.io

sonar.sources=crates
sonar.tests=crates
sonar.source.inclusions=**/src/**/*.rs
sonar.test.inclusions=**/tests/**/*.rs
sonar.exclusions=**/target/**,contracts/**,**/proto/**,**/build.rs

sonar.coverageReportPaths=coverage/sonar-coverage.xml

sonar.cpd.minimumTokens=50
sonar.cpd.minimumLines=10

sonar.scm.provider=git
