//! `export-poseidon` subcommand: emit the exact BN254 Poseidon constants and
//! reference vectors used by the circuit, so the on-chain `PoseidonBN254`
//! library can reproduce the settlement hash-chain byte-for-byte (#209) and so
//! the parameter set carries an independent reference vector (#232).
//!
//! The constants come straight from the shared `dp_poseidon::poseidon_config`
//! source (re-exported by [`dp_zk::pedersen::poseidon_config`]), so the
//! generated Solidity is regenerable and never hand-transcribed.

use std::process::ExitCode;

use ark_bn254::Fr;
use ark_crypto_primitives::sponge::poseidon::{PoseidonConfig, PoseidonSponge};
use ark_crypto_primitives::sponge::CryptographicSponge;
use ark_ff::PrimeField;
use clap::Parser;
use dp_zk::pedersen::{poseidon_config, settlement_chain, SettlementRow};

#[derive(Parser, Debug)]
pub struct ExportPoseidonArgs {
    /// Emit a ready-to-commit Solidity `PoseidonConstants` library instead of
    /// the default JSON (config + ark/mds + reference vectors).
    #[arg(long)]
    pub sol: bool,
}

/// Canonical decimal string of a field element (matches Solidity `uint256`).
fn dec(f: Fr) -> String {
    f.into_bigint().to_string()
}

/// `poseidon(inputs)` via the same sponge the circuit uses (absorb-then-squeeze
/// one element). Used to publish a raw-permutation reference vector.
fn poseidon_n(inputs: &[Fr]) -> Fr {
    let cfg = poseidon_config();
    let mut sponge = PoseidonSponge::<Fr>::new(&cfg);
    sponge.absorb(&inputs.to_vec());
    sponge.squeeze_field_elements::<Fr>(1)[0]
}

/// A fixed two-row settlement chain (acc0 = 0). Mirrors the `eth_submitter`
/// test match (bid 0x10, ask 0x20, price 100, size 10) at the 1e8 scale, plus a
/// second distinct row, so the Solidity port has a multi-row chain to check.
fn reference_rows() -> Vec<SettlementRow> {
    vec![
        SettlementRow {
            bid_addr: Fr::from(0x10u64),
            ask_addr: Fr::from(0x20u64),
            price: Fr::from(10_000_000_000u64), // 100 * 1e8
            size: Fr::from(1_000_000_000u64),   // 10 * 1e8
        },
        SettlementRow {
            bid_addr: Fr::from(0x11u64),
            ask_addr: Fr::from(0x21u64),
            price: Fr::from(20_000_000_000u64), // 200 * 1e8
            size: Fr::from(2_000_000_000u64),   // 20 * 1e8
        },
    ]
}

fn vectors_json() -> serde_json::Value {
    let p5 = poseidon_n(&[
        Fr::from(1u64),
        Fr::from(2u64),
        Fr::from(3u64),
        Fr::from(4u64),
        Fr::from(5u64),
    ]);
    let rows = reference_rows();
    let chain = settlement_chain(Fr::from(0u64), &rows);
    serde_json::json!({
        "poseidon5_1_2_3_4_5": dec(p5),
        "chain2": {
            "acc0": "0",
            "rows": rows.iter().map(|r| serde_json::json!({
                "bidAddr": dec(r.bid_addr),
                "askAddr": dec(r.ask_addr),
                "price": dec(r.price),
                "size": dec(r.size),
            })).collect::<Vec<_>>(),
            "result": dec(chain),
        }
    })
}

fn emit_json(cfg: &PoseidonConfig<Fr>) -> String {
    let ark: Vec<Vec<String>> = cfg
        .ark
        .iter()
        .map(|row| row.iter().map(|f| dec(*f)).collect())
        .collect();
    let mds: Vec<Vec<String>> = cfg
        .mds
        .iter()
        .map(|row| row.iter().map(|f| dec(*f)).collect())
        .collect();
    let value = serde_json::json!({
        "fieldModulus": Fr::MODULUS.to_string(),
        "fullRounds": cfg.full_rounds,
        "partialRounds": cfg.partial_rounds,
        "alpha": cfg.alpha,
        "rate": cfg.rate,
        "capacity": cfg.capacity,
        "ark": ark,
        "mds": mds,
        "vectors": vectors_json(),
    });
    serde_json::to_string_pretty(&value).expect("json")
}

fn emit_sol(cfg: &PoseidonConfig<Fr>) -> String {
    let mut s = String::new();
    s.push_str("// SPDX-License-Identifier: MIT\n");
    s.push_str(
        "// GENERATED by `cargo run -p dp-zk-cli -- export-poseidon --sol`. DO NOT EDIT BY HAND.\n",
    );
    s.push_str(
        "// Source of truth: dp_poseidon::poseidon_config \
         (re-exported by dp_zk::pedersen::poseidon_config).\n",
    );
    s.push_str("// Regenerate after any Poseidon-config change and re-run the cross-language\n");
    s.push_str("// vector test in contracts/test/PoseidonBN254.t.sol.\n");
    s.push_str("pragma solidity ^0.8.24;\n\n");
    s.push_str("/// arkworks BN254 Poseidon round constants (ark) and MDS matrix for the\n");
    s.push_str("/// t=3 (rate 2, capacity 1), 8 full + 57 partial, x^5 configuration.\n");
    s.push_str("library PoseidonConstants {\n");

    s.push_str(&format!(
        "    uint256 internal constant FIELD_MODULUS = {};\n\n",
        Fr::MODULUS
    ));

    s.push_str(&format!(
        "    /// Round constants, indexed [round][element]; {} rounds x {} elements.\n",
        cfg.ark.len(),
        cfg.ark.first().map(|r| r.len()).unwrap_or(0)
    ));
    s.push_str("    function ark() internal pure returns (uint256[3][65] memory a) {\n");
    for (i, row) in cfg.ark.iter().enumerate() {
        for (j, f) in row.iter().enumerate() {
            s.push_str(&format!("        a[{i}][{j}] = {};\n", dec(*f)));
        }
    }
    s.push_str("    }\n\n");

    s.push_str("    /// MDS matrix, indexed [row][col]; 3 x 3.\n");
    s.push_str("    function mds() internal pure returns (uint256[3][3] memory m) {\n");
    for (i, row) in cfg.mds.iter().enumerate() {
        for (j, f) in row.iter().enumerate() {
            s.push_str(&format!("        m[{i}][{j}] = {};\n", dec(*f)));
        }
    }
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

pub fn run_export_poseidon(args: ExportPoseidonArgs) -> ExitCode {
    let cfg = poseidon_config();
    let out = if args.sol {
        emit_sol(&cfg)
    } else {
        emit_json(&cfg)
    };
    println!("{out}");
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Lock the published reference vectors. These are the exact targets the
    /// Solidity `PoseidonBN254` library is checked against in
    /// `contracts/test/PoseidonBN254.t.sol`; if an arkworks or Poseidon-config
    /// change ever moves them, this trips before the on-chain port can silently
    /// desync from the circuit. The `chain2` value additionally flows through
    /// the shared `settlement_chain`, which `dp-zk`'s circuit test pins to the
    /// in-circuit `settlement_acc`.
    #[test]
    fn reference_vectors_are_stable() {
        let p5 = poseidon_n(&[
            Fr::from(1u64),
            Fr::from(2u64),
            Fr::from(3u64),
            Fr::from(4u64),
            Fr::from(5u64),
        ]);
        assert_eq!(
            dec(p5),
            "17202221768493126381180179227250714636677047994833944093631184439391269770327",
        );

        let chain = settlement_chain(Fr::from(0u64), &reference_rows());
        assert_eq!(
            dec(chain),
            "13176863867183045156691872925194891460694388274017740522862028043601348896898",
        );
    }

    /// `PoseidonConstants.sol` is generated by `emit_sol`, never edited by hand,
    /// so the committed file must be byte-for-byte what the generator emits. The
    /// vector test catches wrong *values*; this catches a stale generated file —
    /// e.g. a config change committed without regenerating the Solidity.
    #[test]
    fn emitted_sol_matches_committed_constants() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .join("contracts")
            .join("src")
            .join("PoseidonConstants.sol");
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
            .replace("\r\n", "\n");
        // The committed file is `emit_sol` output written through the CLI, whose
        // `println!` appends one trailing newline. Compare ignoring trailing
        // whitespace so only real content drift trips this.
        assert_eq!(
            emit_sol(&poseidon_config()).trim_end(),
            committed.trim_end(),
            "PoseidonConstants.sol is stale — regenerate with \
             `cargo run -p dp-zk-cli -- export-poseidon --sol > contracts/src/PoseidonConstants.sol`"
        );
    }

    /// The JSON export must carry the full config (65x3 ark, 3x3 mds, round
    /// counts) and the same locked reference vectors the Solidity port checks.
    #[test]
    fn emit_json_exposes_config_and_vectors() {
        let v: serde_json::Value =
            serde_json::from_str(&emit_json(&poseidon_config())).expect("valid json");
        assert_eq!(v["fullRounds"].as_u64(), Some(8));
        assert_eq!(v["partialRounds"].as_u64(), Some(57));
        assert_eq!(v["ark"].as_array().map(Vec::len), Some(65));
        assert_eq!(v["ark"][0].as_array().map(Vec::len), Some(3));
        assert_eq!(v["mds"].as_array().map(Vec::len), Some(3));
        assert_eq!(
            v["vectors"]["poseidon5_1_2_3_4_5"],
            serde_json::json!(
                "17202221768493126381180179227250714636677047994833944093631184439391269770327"
            )
        );
        assert_eq!(
            v["vectors"]["chain2"]["result"],
            serde_json::json!(
                "13176863867183045156691872925194891460694388274017740522862028043601348896898"
            )
        );
    }

    /// Both emitters dispatch and run without panicking.
    #[test]
    fn run_export_poseidon_runs_both_modes() {
        let _ = run_export_poseidon(ExportPoseidonArgs { sol: false });
        let _ = run_export_poseidon(ExportPoseidonArgs { sol: true });
    }
}
