#!/usr/bin/env bash
#
# Writes front/lib/prover/zk-pkg/BUILDINFO, stamping the committed browser
# artifacts with a hash of the sources that produced them. Called by
# `just build-wasm-zk`; the WASM (dp-zk-wasm) CI job recomputes the hash and
# compares it against the recorded value.
set -euo pipefail

cd "$(dirname "$0")/.."

hash=$(./scripts/zk-artifact-hash.sh)

cat > front/lib/prover/zk-pkg/BUILDINFO <<EOF
# Generated by \`just build-wasm-zk\`. Do not edit by hand.
#
# sha256 over the sources that produced the artifacts in this directory —
# see scripts/zk-artifact-hash.sh for what goes into it and why the .wasm
# bytes themselves are not compared. Regenerate both together.
sources: $hash
EOF
