[package]
name = "dp-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
dp-auction = { path = "../dp-auction" }
dp-zk = { path = "../dp-zk" }
uuid = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"

[dev-dependencies]
dp-types = { path = "../dp-types" }
dp-zk-cli = { path = "../dp-zk-cli" }
hex = { workspace = true }
tempfile = "3"
