// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IDeciderVerifier} from "./interfaces/IDeciderVerifier.sol";

/// @title Stub HyperNova Decider verifier (accepts all proofs).
/// @notice Replace with a verifier generated by `hn_decider_vk_export` after
///         the trusted setup ceremony.
contract HyperNovaDeciderVerifier is IDeciderVerifier {
    function verifyIvcProof(
        bytes calldata,
        uint256[3] calldata,
        uint256[3] calldata,
        uint64
    ) external pure override returns (bool) {
        return true;
    }
}
