// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IDeciderVerifier} from "./interfaces/IDeciderVerifier.sol";

/// @title Stub HyperNova Decider verifier (accepts all proofs).
/// @notice Replace with a verifier generated by `hn_decider_vk_export` after
///         the trusted setup ceremony (#210). Until then `zN` is unconstrained,
///         so the `settleAuction` settlement binding (#209) — which checks
///         `matches[]` against `zN[3]` — is structurally in place but not yet
///         cryptographically enforced: a stubbed proof lets the operator pick
///         any `zN`. This stub MUST NOT be deployed to production.
contract HyperNovaDeciderVerifier is IDeciderVerifier {
    function verifyIvcProof(
        bytes calldata,
        uint256[5] calldata,
        uint256[5] calldata,
        uint64
    ) external pure override returns (bool) {
        return true;
    }
}
